### ISSUE TITLE
Переполнение буфера

### ISSUE THREAD

**Issue by KittaLaten** [Dovgalyuk/RETasks#54]
[Мисилин 2096 buffer.docx](https://github.com/Dovgalyuk/RETasks/files/10294769/2096.buffer.docx)

**Comment by Dovgalyuk** [comment]
1. Адреса на картинках и в тексте не сходятся
2. Нужно либо использовать предоставленные бинарные файлы, либо скомпилировать их без защиты стека (на картинке показана неудачная попытка компиляции)
